config/routes.rb
ETouhou::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => "home#index"
  #resources :pages


  resources :comics do
    resources :pages do
      resources :bilis
    end
    resources :comments
  end

  match 'tags' => 'comics#tag_cloud'
  match 'tags/:tag' => 'comics#tagged', :as => 'tagged'

  resources :comments


  resources :characters


  resources :categories


  authenticated :user do
    root :to => 'comics#index'
  end
  #root :to => "comics#index"
  devise_for :users
  resources :users
end

app/models/comic.rb
class Comic < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  attr_accessible :artist, :finished, :name, :publish, :translator, :under_review, :x_rated
  attr_accessible :user_id, :category_id, :pages_attributes, :tag_list
  has_many :pages, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  accepts_nested_attributes_for :pages, :allow_destroy => true


  validates :user, :presence => true
  validates :category, :presence => true
  validates :name, :presence => true
  validates :pages, :length => { :minimum => 1 }

  acts_as_taggable
  acts_as_votable
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  authorize_resource
  # GET /comics
  # GET /comics.json
  respond_to :html, :json
  def index
    @comics = Comic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comics }
    end
  end

  # GET /comics/1
  # GET /comics/1.json
  def show

    @comic = Comic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comic }
    end
  end

  # GET /comics/new
  # GET /comics/new.json
  def new
    @comic = Comic.new
    5.times { @comic.pages.build }
    respond_with(@comic)
  end

  # GET /comics/1/edit
  def edit
    @comic = Comic.find(params[:id])
    5.times { @comic.pages.build }
  end

  # POST /comics
  # POST /comics.json
  def create
    @comic = Comic.new(params[:comic])
    @comic.user = current_user
    @comic.under_review = true

    respond_to do |format|
      if @comic.save
        format.html { redirect_to @comic, notice: 'Comic was successfully created.' }
        format.json { render json: @comic, status: :created, location: @comic }
      else
        format.html { render action: "new" }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comics/1
  # PUT /comics/1.json
  def update
    @comic = Comic.find(params[:id])

    respond_to do |format|
      if @comic.update_attributes(params[:comic])
        format.html { redirect_to @comic, notice: 'Comic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comics/1
  # DELETE /comics/1.json
  def destroy
    @comic = Comic.find(params[:id])
    @comic.destroy

    respond_to do |format|
      format.html { redirect_to comics_url }
      format.json { head :no_content }
    end
  end

  def tagged
    #if params[:tag].present?
      @comics = Comic.tagged_with(params[:tag])
    #else
    #  @comics = Comic.postall
    #end
  end
  def tag_cloud
    @tags = Comic.tag_counts_on(:tags)
  end
end

app/helpers/comics_helper.rb
module ComicsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/comics/_form.html.erb
<%= simple_form_for(@comic) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :finished %>
      <%= f.input :artist %>
      <%= f.association :category %>
      <%= f.input :translator %>
      <%= f.input :publish %>
      <%= f.input :x_rated %>
      <%= f.input :tag_list, label: Comic.human_attribute_name(:tags) %>
      <%= f.fields_for :pages do |page| %>

          <% if page.object.new_record? %>
              <%= page.file_field :attachment %>
          <% else %>
              <div class="thumbnail">
                <%= link_to(image_tag(page.object.attachment.url(:thumb)), page.object.attachment.url(:original)) %>
                <%= page.check_box :_destroy %>
              </div>
          <% end %>
      <% end %>
    </div>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>

app/views/comics/edit.html.erb
<h1>Editing comic</h1>

<%= render 'form' %>

<%= link_to 'Show', @comic %> |
<%= link_to 'Back', comics_path %>

app/views/comics/index.html.erb
<h1>Listing comics</h1>

<table>
  <tr>
    <th>Name</th>
    <th>User</th>
    <th>Finished</th>
    <th>Artist</th>
    <th>Category</th>
    <th>Translator</th>
    <th>Publish</th>
    <th>X rated</th>
    <th>Under review</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comics.each do |comic| %>
  <tr>
    <td><%= comic.name %></td>
    <td><%= render comic.user %></td>
    <td><%= comic.finished %></td>
    <td><%= comic.artist %></td>
    <td><%= link_to comic.category.name, comic.category %></td>
    <td><%= comic.translator %></td>
    <td><%= comic.publish %></td>
    <td><%= comic.x_rated %></td>
    <td><%= comic.under_review %></td>
    <td><%= link_to 'Show', comic %></td>
    <td><%= link_to 'Edit', edit_comic_path(comic) %></td>
    <td><%= link_to 'Destroy', comic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comic', new_comic_path %>

app/views/comics/new.html.erb
<h1>New comic</h1>

<%= render 'form' %>

<%= link_to 'Back', comics_path %>

app/views/comics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @comic.name %>
</p>

<p>
  <b>User:</b>
  <%= render @comic.user %>
</p>

<p>
  <b>Finished:</b>
  <%= @comic.finished %>
</p>

<p>
  <b>Artist:</b>
  <%= @comic.artist %>
</p>

<p>
  <b>Category:</b>
  <%= link_to @comic.category.name, @comic.category %>
</p>

<p>
  <b>Translator:</b>
  <%= @comic.translator %>
</p>

<p>
  <b>Publish:</b>
  <%= @comic.publish %>
</p>

<p>
  <b>X rated:</b>
  <%= @comic.x_rated %>
</p>

<p>
  <b>Under review:</b>
  <%= @comic.under_review %>
</p>

<% @comic.tags.any? %>
<% @comic.tags.each do |tag| %>
    <%= link_to tag.name, tagged_url(:tag => tag.name) %>
<% end %>

<% @comic.pages.each do |page| %>
    <%= link_to(image_tag(page.attachment.url(:thumb)), comic_page_path(@comic, page)) %>
<% end %>

<h2>Comments</h2>
<% @comic.comments.each do |comment| %>
    <p>
      <b>Commenter:</b>
      <%= render comment.user %>
    </p>

    <p>
      <b>Comment:</b>
      <%= comment.content %>
    </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_for([@comic, @comic.comments.build]) do |f| %>
    <div class="field">
      <%= f.label :content %><br />
      <%= f.text_area :content %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<%= link_to 'Edit', edit_comic_path(@comic) %> |
<%= link_to 'Back', comics_path %>

app/views/comics/tag_cloud.html.erb
<% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
    <%= link_to tag.name, { :action => :tagged, :controller => :comics, :tag => tag.name }, :class => css_class %>
<% end %>

app/views/comics/tagged.html.erb
<h1>Listing comics</h1>

<table>
  <tr>
    <th>Name</th>
    <th>User</th>
    <th>Finished</th>
    <th>Artist</th>
    <th>Category</th>
    <th>Translator</th>
    <th>Publish</th>
    <th>X rated</th>
    <th>Under review</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comics.each do |comic| %>
  <tr>
    <td><%= comic.name %></td>
    <td><%= render comic.user %></td>
    <td><%= comic.finished %></td>
    <td><%= comic.artist %></td>
    <td><%= link_to comic.category.name, comic.category %></td>
    <td><%= comic.translator %></td>
    <td><%= comic.publish %></td>
    <td><%= comic.x_rated %></td>
    <td><%= comic.under_review %></td>
    <td><%= link_to 'Show', comic %></td>
    <td><%= link_to 'Edit', edit_comic_path(comic) %></td>
    <td><%= link_to 'Destroy', comic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comic', new_comic_path %>