config/routes.rb
ETouhou::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => "home#index"
  #resources :pages


  resources :comics do
    resources :pages do
      resources :bilis
    end
    resources :comments
  end

  match 'tags' => 'comics#tag_cloud'
  match 'tags/:tag' => 'comics#tagged', :as => 'tagged'

  resources :comments


  resources :characters


  resources :categories


  authenticated :user do
    root :to => 'comics#index'
  end
  #root :to => "comics#index"
  devise_for :users
  resources :users
end

app/models/bili.rb
class Bili < ActiveRecord::Base
  belongs_to :page
  belongs_to :user
  attr_accessible :content,:x, :y
  attr_accessible :user_id
end

app/controllers/bilis_controller.rb
class BilisController < ApplicationController
  # GET /bilis
  # GET /bilis.json
  def index
    @bilis = Bili.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bilis }
    end
  end

  # GET /bilis/1
  # GET /bilis/1.json
  def show
    @bili = Bili.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bili }
    end
  end

  # GET /bilis/new
  # GET /bilis/new.json
  def new
    @bili = Bili.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bili }
    end
  end

  # GET /bilis/1/edit
  def edit
    @bili = Bili.find(params[:id])
  end

  # POST /bilis
  # POST /bilis.json
  def create
    @page = Page.find(params[:page_id])
    @bili = @page.bilis.create(params[:bili].merge({user_id: current_user.id}))
    redirect_to comic_page_path(@page.comic, @page)
  end

  # PUT /bilis/1
  # PUT /bilis/1.json
  def update
    @bili = Bili.find(params[:id])

    respond_to do |format|
      if @bili.update_attributes(params[:bili])
        format.html { redirect_to @bili, notice: 'Bili was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bili.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bilis/1
  # DELETE /bilis/1.json
  def destroy
    @bili = Bili.find(params[:id])
    @bili.destroy

    respond_to do |format|
      format.html { redirect_to bilis_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/bilis_helper.rb
module BilisHelper
end

app/views/bilis/_form.html.erb
<%= simple_form_for(@bili) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :page %>
    <%= f.input :user %>
    <%= f.input :content %>
    <%= f.input :x %>
    <%= f.input :y %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bilis/edit.html.erb
<h1>Editing bili</h1>

<%= render 'form' %>

<%= link_to 'Show', @bili %> |
<%= link_to 'Back', bilis_path %>

app/views/bilis/index.html.erb
<h1>Listing bilis</h1>

<table>
  <tr>
    <th>Page</th>
    <th>User</th>
    <th>Content</th>
    <th>X</th>
    <th>Y</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bilis.each do |bili| %>
  <tr>
    <td><%= bili.page %></td>
    <td><%= bili.user %></td>
    <td><%= bili.content %></td>
    <td><%= bili.x %></td>
    <td><%= bili.y %></td>
    <td><%= link_to 'Show', bili %></td>
    <td><%= link_to 'Edit', edit_bili_path(bili) %></td>
    <td><%= link_to 'Destroy', bili, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bili', new_bili_path %>

app/views/bilis/new.html.erb
<h1>New bili</h1>

<%= render 'form' %>

<%= link_to 'Back', bilis_path %>

app/views/bilis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Page:</b>
  <%= @bili.page %>
</p>

<p>
  <b>User:</b>
  <%= @bili.user %>
</p>

<p>
  <b>Content:</b>
  <%= @bili.content %>
</p>

<p>
  <b>X:</b>
  <%= @bili.x %>
</p>

<p>
  <b>Y:</b>
  <%= @bili.y %>
</p>


<%= link_to 'Edit', edit_bili_path(@bili) %> |
<%= link_to 'Back', bilis_path %>