config/routes.rb
ETouhou::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => "home#index"
  #resources :pages


  resources :comics do
    resources :pages do
      resources :bilis
    end
    resources :comments
  end

  match 'tags' => 'comics#tag_cloud'
  match 'tags/:tag' => 'comics#tagged', :as => 'tagged'

  resources :comments


  resources :characters


  resources :categories


  authenticated :user do
    root :to => 'comics#index'
  end
  #root :to => "comics#index"
  devise_for :users
  resources :users
end

app/views/pages/_form.html.erb
<%= simple_form_for(@page, :html => {:multipart => true} ) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :comic %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Comic</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.comic %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Comic:</b>
  <%= @page.comic %>
  <%= image_tag(@page.attachment.url(:large)) %>
</p>


<h2>Comments</h2>
<% @page.bilis.each do |bili| %>
    <p>
      <b>Commenter:</b>
      <%= render bili.user %>
    </p>

    <p>
      <b>Comment:</b>
      <%= bili.content %>
    </p>
<% end %>

<h2>Add a comment:</h2>


<%= simple_form_for([@page, @page.bilis.build], :url => comic_page_bilis_path(@page.comic, @page)) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :x %>
      <%= f.input :y %>
      <%= f.input :content %>
    </div>
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>



<%= link_to 'Edit', edit_comic_page_path(@page.comic, @page) %> |
<%= link_to 'Back', @page.comic %>